[
  {
    id: 'ethereum-renzo-ezeth-staking',
    name: 'Renzo Restaking',
    content: null,
    apy: 0.0392762000394306,
    metadata_type: 'restaking',
    token_network: 'ethereum',
    token_symbol: 'ETH',
    token_address: null,
    provider_id: 'renzo',
    provider_name: 'Renzo',
    protocol: 'renzo',
    asset: 'ETH',
    tvl: 0,
    cooldown_days: null,
    warmup_days: null,
    withdraw_days: null
  },
  {
    id: 'ethereum-eth-etherfi-staking',
    name: 'Ether.fi Restaking',
    content: null,
    apy: 0.0354267875115386,
    metadata_type: 'restaking',
    token_network: 'ethereum',
    token_symbol: 'ETH',
    token_address: null,
    provider_id: 'etherfi',
    provider_name: 'Ether.fi',
    protocol: 'ether.fi',
    asset: 'ETH',
    tvl: 0,
    cooldown_days: 7,
    warmup_days: null,
    withdraw_days: null
  },
  {
    id: 'ethereum-eth-everstake-staking',
    name: 'Everstake Pooled ETH Staking',
    content: null,
    apy: 0.0349892654549052,
    metadata_type: 'staking',
    token_network: 'ethereum',
    token_symbol: 'ETH',
    token_address: null,
    provider_id: 'everstake',
    provider_name: 'Everstake',
    protocol: 'everstake',
    asset: 'ETH',
    tvl: 0,
    cooldown_days: 9,
    warmup_days: 2,
    withdraw_days: null
  },
  {
    id: 'ethereum-eth-luganodes-staking',
    name: 'Luganodes Native Staking',
    content: null,
    apy: 0.0323,
    metadata_type: 'staking',
    token_network: 'ethereum',
    token_symbol: 'ETH',
    token_address: null,
    provider_id: 'luganodes',
    provider_name: 'Luganodes',
    protocol: 'luganodes',
    asset: 'ETH',
    tvl: 0,
    cooldown_days: 1,
    warmup_days: 8,
    withdraw_days: null
  },
  {
    id: 'ethereum-eth-p2p-staking',
    name: 'P2P.org Native Staking',
    content: null,
    apy: 0.0319584355553912,
    metadata_type: 'staking',
    token_network: 'ethereum',
    token_symbol: 'ETH',
    token_address: null,
    provider_id: 'P2P',
    provider_name: 'P2P.org',
    protocol: 'p2p.org',
    asset: 'ETH',
    tvl: 0,
    cooldown_days: 1,
    warmup_days: 8,
    withdraw_days: null
  }
]