packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bufferutil
  - esbuild
  - keccak
  - prisma
  - sharp
  - unrs-resolver
  - utf-8-validate
